name: GCP Bucket Deploy
on: workflow_dispatch       # set the triggers to your liking
#   push:
#     branches: [ main ]

jobs:
  job_id:
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v7'

    - id: 'auth'
      uses: 'google-github-actions/auth@v3'
      with:
        service_account: '${{vars.SERVICE_ACCOUNT}}'

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@v3'
      with:
        path: 'myfolder'
        glob: '**/*.html'
        parent: false
        destination: '${{vars.BUCKET_NAME}}'

    # Example of using the output
    - id: 'uploaded-files'
      uses: 'foo/bar@v1'
      env:
        file: '${{ steps.upload-files.outputs.uploaded }}'
